### PR TITLE
Assert.AreEqual methods for TStrings and Assert.NoDiff for comparing strings with extended description on failure

### PR DESCRIPTION
**Pull request by plathub**
These methods are pretty useful for checking large strings and string lists. 
`NoDiff` raises some handy test failures if the strings are not equal, for example:

`Assert.NoDiff('abc', 'abcd');`
will raise `Length of strings is not equal: Expected 3 but got 4  `

`Assert.NoDiff('lorem ipsum', 'lorem Ipsum');`
will raise `Difference at position 7: ['ipsum'] does not match ['Ipsum'] `

The difference might be obvious in the above example, but it becomes difficult on long or cryptic strings to find where the difference is.

`NoDiff` is also utilized in `Assert.AreEqual` for `TStrings` objects.

```
expectedStrings.CommaText := '"Lorem ipsum dolor sit amet","consectetur adipisici elit"';
actualStrings.CommaText := '"Lorem ipsum dolor sit amet","consectetur adisipici elit"';
Assert.AreEqual(expectedStrings, actualStrings);
```
will raise `Difference at position 16: [''pisici eli''] does not match [''sipici eli''] at line 2`

`AreEqual` for `TStrings` is also very helpful for comparing text files and this function could be the base for a corresponding function in the apparently upcoming `FileAssert` unit by @rmcginty.

### CODE REVIEW

**Comment by vincentparrett** [comment]
Thanks for the contribution, looks useful.

I just merged another PR which is now causing merge conflicts with this one - please merge 
upstream/master with your branch to resolve the conflicts and push again.

**Comment by plathub** [comment]
done

**Comment by vincentparrett** [comment]
Thanks for the contribution.

**Comment by rmcginty** [comment]
Yeah, I like this too @plathub.  While I use my visual diffing in the GUI most of the time, I did have a gap in functionality when it came to the other loggers when comparing anything bigger than a line or two.  I will definitely make sure the FileAssert makes use of it as well.

**Pull request merged**
