### PR TITLE
Check expectation assert.

### PR DESCRIPTION
**Pull request by henriquewerlang**

### CODE REVIEW

**Comment by henriquewerlang** [comment]
Can anyone accept this pull request?

**Comment by vincentparrett** [comment]
I'm not entirely sure what it is this does? Can you provide and example of how/where it would be used?

**Comment by henriquewerlang** [comment]
It is used with Delphi.Mocks, to show a message saying that a configured expectation has not been reached. Currently I use the IsEmpty of a string, but the default message does not close with the Mock scheme. That's why I created this new assert, to show a clearer message to the programmer.

**Comment by henriquewerlang** [comment]
?

**Comment by vincentparrett** [comment]
This seems unnecessary to me, and will also not compile in earlier versions due to the use of string IsEmpty.  I guess it's name is confusing, as it doesn't check an expectation, it just checks for an empty string.

Perhaps a better approach would be to add an overload for IsEmpty

````delphi
class procedure IsEmpty(const value : string; const formatStr : string; const message : string = '');overload;
````

**Comment by vincentparrett** [comment]
This PR does not compile with older versions of delphi due to the use of the string helper IsEmpty.

**Pull request merged**
