### PR TITLE
Live Templates intallation

### PR DESCRIPTION
**Pull request by henriquewerlang**
Modificado o instalador do Live Templates, para funcionar com a pasta da Embarcadeiro e não apenas com a do Radstudio.

### CODE REVIEW

**Comment by rpottsoh** [comment]
As it is written this batch file will always favor older versions of Delphi.  Systems that have both new and old versions installed have a 50 50 chance of having a bad outcome.... (or a good one).....  There should perhaps be two batch files, one that favors older versions of delphi and one that favors newer versions.

**Comment by henriquewerlang** [comment]
Adicionei um ajuste no DPR, para o Test Insight

**Comment by henriquewerlang** [comment]
> As it is written this batch file will always favor older versions of Delphi.  Systems that have both new and old versions installed have a 50 50 chance of having a bad outcome.... (or a good one).....  There should perhaps be two batch files, one that favors older versions of delphi and one that favors newer versions.

**Comment by henriquewerlang** [comment]
Fechei sem querer.

**Pull request closed without merging**
