### PR TITLE
Report leak config in the wizard.

### PR DESCRIPTION
**Pull request by henriquewerlang**
Changed the new project wizard, to select the type of report leak, and create the project with the type selected.

### CODE REVIEW

**Comment by vincentparrett** [comment]
Looks good, thanks.

**Comment by henriquewerlang** [comment]
I'm using this my implementation and found a problem, you must uncommit.
I'll send the adjustment for everything to work.

**Comment by vincentparrett** [comment]
Hmm.. our CI setup doesn't build the wizard so I didn't notice. Need to fix that. It's currently only building for XE7, I need to spend some time on this to build for every supported version.

**Comment by henriquewerlang** [comment]
I just sent the adjustment, in the #303.

**Pull request merged**
