### PR TITLE
Fixture sorting.

### PR DESCRIPTION
**Pull request by henriquewerlang**
I just implemented the ordering of the results, so that the integration with the IDE gets better.

### CODE REVIEW

**Comment by vincentparrett** [comment]
Please undo the formatting changes

**Comment by henriquewerlang** [comment]
Sure, but may I ask why?

**Comment by vincentparrett** [comment]
2 reasons

1) I prefer all lower case for intrisic types
2) It's bad etiquette to apply **your** formatting preferences in a pull request, PR's should only contain the changes that are actually needed. For formatting changes, discuss with the repo owner first.

**Comment by luebbe** [comment]
Concerning formatting changes: I'd love to see a delphi formatter config with the project's style in every delphi open source repo. Since I type Ctrl+D more often than Ctrl+F9, I often mess up formatting accidentally and have to undo it.

**Comment by henriquewerlang** [comment]
Changed.

**Comment by henriquewerlang** [comment]
Can accept now?

**Pull request merged**
