### PR TITLE
Issue 226

### PR DESCRIPTION
**Pull request by michaelstaszewski**
#226 fix.

I am on 10.1 Berlin and have no other Delphi versions to test with.

### CODE REVIEW

**Comment by michaelstaszewski** [comment]
I'm fairly new to Git and not sure why that other commit from 6d ago is showing here with the pull request when it seems to be part of the upstream repository now and I've done followed the [instructions here](https://help.github.com/articles/syncing-a-fork/) to sync my fork with the upstream. Only the commit for issue #226 is of interest.

**Comment by michaelstaszewski** [comment]
This change is an immediate fix to the issue at hand. I see the flag there to ignore fixture setup when a constructor exists, but I'm not sure of the expectation when a base class constructor is not overridden in the derived.

**Comment by michaelstaszewski** [comment]
Sounds good, thanks. I was in a pinch and needed a fix and found @Malte's answer to [this question](https://stackoverflow.com/questions/791069) and it seems to work in all of my test cases, but I'm limited to 10.1 Berlin at the moment.

**Comment by vincentparrett** [comment]
Not merging, a better fix has been pushed.

**Pull request closed without merging**
