### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by MartinSedgewick**
- Removed MadExcept from the XE7 Examples dpr
- Fix to Assert.StartsWith and EndsWith, which had the subString and theString parameters the wrong way around ( in XE7 anyway).
- added tests for these asserts to Assert test fixture

### CODE REVIEW

**Comment by MartinSedgewick** [comment]
Sorry about the reverts, I am not used to Github and still find it awkward to use.

Let me know if there are any changes required.

**Comment by MartinSedgewick** [comment]
Forgot to say that I swapped around the parameters on the Assert, as I thought that, like me, anyone who noticed this issue would have swapped their parameters in their test to make it work. Therefore, this way keeps is working, without having to fix tests.

**Comment by sglienke** [comment]
To be honest I never understood why StartsText and alike have the substring first. In my mind that is the wrong order. And if you think in the context of the new instrinsic helpers who have the StartsWith method you say myStr.StartsWith('foo'). Naturally the <self> argument is the first one.

**Comment by vincentparrett** [comment]
Um, why did you revert the MaxTimeAttribute stuff? I just realised it was not in the pull request.

**Pull request merged**
